### ISSUE TITLE
Single braces

### ISSUE THREAD

**Issue by lucascurti** [FabioAntunes/double-brackets-with-spaces#2]
Hi @FabioAntunes . Nice package! Can you do a version that also supports single braces?

**Comment by FabioAntunes** [comment]
Thanks @lucatros I could add that functionality, but probably as an optional setting. It might annoy a lot of people, since we use a lot of single braces in code

**Comment by lucascurti** [comment]
I see what you mean. I was thinking it might be good for cases like ES6 imports:
`import { render } from 'react-dom';` 

But, as you mentioned, it will be a problem when typing a single brace as part of a Block. Maybe you can trigger it when a space is typed after the opening curly brace.

**Comment by FabioAntunes** [comment]
Hmmm, I could create a rule just for ES6 imports, like if there's an `import` in the line then add the spaces

**Comment by lucascurti** [comment]
Sounds perfect to me. I'll let you know if I find any other cases where it might be useful

**Comment by FabioAntunes** [comment]
@lucatros Released a new version, you can go to settings and enable spaces for single brackets

**Comment by lucascurti** [comment]
Lovely! Thanks @FabioAntunes
